In [3]:
import pandas as pd
import joblib
import numpy as np

In [4]:
conns = joblib.load('../data/costas-graph/CONNS.dat')
conns_test = joblib.load('../data/costas-graph/CONNS_test.dat')

In [8]:
conns['dsgdb9nsd_000001']

array([[0, 1, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]])

In [9]:
conns_test['dsgdb9nsd_000004']

array([[0, 3, 0, 1],
       [3, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [10]:
t = np.stack(conns_test['dsgdb9nsd_000004'])

In [15]:
np.identity(4)[np.sum(t, 1) - 1]

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [20]:
np.sum(conns_test['dsgdb9nsd_000015'], 1)

array([4, 2, 4, 1, 1, 1, 1, 1, 1])